# User
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: rafa
  name: rafa
spec:
  displayName: Rafa
  email: rapez@acc.com

---

# Group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: rafa
  name: rafa
spec:
  type: team
  description: Grupo de desarrolladores
  email: rapez@acc.com
