# User
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: rafa
  name: rafa
spec:
  displayName: rafa
  email: rafa@acc.com
  memberOf:
    - acc
---
# Group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: acc
  name: acc
spec:
  type: team
  description: Grupo de desarrolladores
  email: acc@acc.com
  children:
    - rafa
